/*
 * This file was automatically generated by Sindri.
 * Do not edit manually.
 */

package app.http.provider.data;

import io.valkyrja.container.data.contract.ContainerDataContract;
import io.valkyrja.container.manager.contract.ContainerContract;

import java.util.Map;
import java.util.function.BiFunction;
import java.util.function.Consumer;

public record AppContainerData() implements ContainerDataContract {

    @Override
    public Map<Class<?>, Class<?>> aliases() {
        return Map.of();
    }

    @Override
    public Map<Class<?>, Consumer<ContainerContract>> callbacks() {
        return Map.of(
            io.valkyrja.container.data.contract.ContainerDataContract.class, app.http.provider.DataServiceProvider::publishContainerData,
            io.valkyrja.event.data.contract.EventDataContract.class, app.http.provider.DataServiceProvider::publishEventData,
            io.valkyrja.http.routing.data.contract.HttpRoutingDataContract.class, app.http.provider.DataServiceProvider::publishHttpRoutingData,
            app.http.controller.HomeController.class, app.http.provider.ServiceProvider::publishHomeController
        );
    }

    @Override
    public Map<Class<?>, BiFunction<ContainerContract, Map<String, Object>, Object>> services() {
        return Map.of();
    }

    @Override
    public Map<Class<?>, Class<?>> singletons() {
        return Map.of();
    }
}
