/*
 * This file was automatically generated by Sindri.
 * Do not edit manually.
 */

package app.http.provider.data;

import io.valkyrja.cli.routing.data.contract.CliRoutingDataContract;
import io.valkyrja.cli.routing.data.contract.RouteContract;

import java.util.Map;
import java.util.function.Supplier;

public record AppCliRoutingData() implements CliRoutingDataContract {

    @Override
    public Map<String, Supplier<RouteContract>> routes() {
        return Map.of();
    }
}
