/*
 * This file was automatically generated by Sindri.
 * Do not edit manually.
 */

package app.http.provider.data;

import io.valkyrja.event.data.contract.EventDataContract;
import io.valkyrja.event.data.contract.ListenerContract;

import java.util.Map;

public record AppEventData() implements EventDataContract {

    @Override
    public Map<Class<?>, Map<String, String>> events() {
        return Map.of();
    }

    @Override
    public Map<String, ListenerContract> listeners() {
        return Map.of();
    }
}
