/*
 * This file was automatically generated by Sindri.
 * Do not edit manually.
 */

package app.http.provider.data;

import io.valkyrja.http.routing.data.contract.HttpRoutingDataContract;
import io.valkyrja.http.routing.data.contract.RouteContract;

import java.util.Map;
import java.util.function.Supplier;

public record AppHttpRoutingData() implements HttpRoutingDataContract {

    @Override
    public Map<String, Supplier<RouteContract>> routes() {
        return Map.of(
            "version", () -> new io.valkyrja.http.routing.data.Route(
                "/version",
                "version",
                app.http.provider.RouteProvider::versionHandler,
                java.util.List.of(io.valkyrja.http.message.enum_.RequestMethod.GET),
                java.util.List.of(), java.util.List.of(), java.util.List.of(),
                java.util.List.of(), java.util.List.of(), null, null
            ),
            "version.post", () -> new io.valkyrja.http.routing.data.Route(
                "/version",
                "version.post",
                app.http.provider.RouteProvider::versionHandler,
                java.util.List.of(io.valkyrja.http.message.enum_.RequestMethod.POST),
                java.util.List.of(), java.util.List.of(), java.util.List.of(),
                java.util.List.of(), java.util.List.of(), null, null
            ),
            "version.put", () -> new io.valkyrja.http.routing.data.Route(
                "/version",
                "version.put",
                app.http.provider.RouteProvider::versionHandler,
                java.util.List.of(io.valkyrja.http.message.enum_.RequestMethod.PUT),
                java.util.List.of(), java.util.List.of(), java.util.List.of(),
                java.util.List.of(), java.util.List.of(), null, null
            ),
            "text", () -> new io.valkyrja.http.routing.data.Route(
                "/text",
                "text",
                app.http.provider.RouteProvider::textHandler,
                java.util.List.of(io.valkyrja.http.message.enum_.RequestMethod.GET),
                java.util.List.of(), java.util.List.of(), java.util.List.of(),
                java.util.List.of(), java.util.List.of(), null, null
            ),
            "welcome", () -> new io.valkyrja.http.routing.data.Route(
                "/",
                "welcome",
                app.http.provider.RouteProvider::welcomeHandler,
                java.util.List.of(io.valkyrja.http.message.enum_.RequestMethod.HEAD, io.valkyrja.http.message.enum_.RequestMethod.GET),
                java.util.List.of(), java.util.List.of(), java.util.List.of(),
                java.util.List.of(), java.util.List.of(), null, null
            ),
            "welcome.cached", () -> new io.valkyrja.http.routing.data.Route(
                "/cached",
                "welcome.cached",
                app.http.provider.RouteProvider::welcomeCachedHandler,
                java.util.List.of(io.valkyrja.http.message.enum_.RequestMethod.HEAD, io.valkyrja.http.message.enum_.RequestMethod.GET),
                java.util.List.of(), java.util.List.of(), java.util.List.of(),
                java.util.List.of(), java.util.List.of(), null, null
            ),
            "home", () -> new io.valkyrja.http.routing.data.Route(
                "/home",
                "home",
                app.http.provider.RouteProvider::homeHandler,
                java.util.List.of(io.valkyrja.http.message.enum_.RequestMethod.HEAD, io.valkyrja.http.message.enum_.RequestMethod.GET),
                java.util.List.of(), java.util.List.of(), java.util.List.of(),
                java.util.List.of(), java.util.List.of(), null, null
            ),
            "json", () -> new io.valkyrja.http.routing.data.Route(
                "/json",
                "json",
                app.http.provider.RouteProvider::jsonHandler,
                java.util.List.of(io.valkyrja.http.message.enum_.RequestMethod.HEAD, io.valkyrja.http.message.enum_.RequestMethod.GET),
                java.util.List.of(), java.util.List.of(), java.util.List.of(),
                java.util.List.of(), java.util.List.of(), null, null
            )
        );
    }

    @Override
    public Map<String, Map<String, String>> paths() {
        return Map.ofEntries(
            Map.entry("GET", Map.of("/version", "version", "/text", "text", "/", "welcome", "/cached", "welcome.cached", "/home", "home", "/json", "json")),
            Map.entry("POST", Map.of("/version", "version.post")),
            Map.entry("PUT", Map.of("/version", "version.put"))
        );
    }

    @Override
    public Map<String, Map<String, String>> dynamicPaths() {
        return Map.of();
    }

    @Override
    public Map<String, Map<String, String>> regexes() {
        return Map.of();
    }
}
