name: Check Outdated Dependencies

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    uses: valkyrjaio/.github/.github/workflows/_java-check-outdated-dependencies.yml@d8c49368481b9270bc9e089b61731dc9b9561be8
    secrets: inherit
    with:
      dependencies: |
        [
          {"name": "Spotless",    "directory": ".github/ci/spotless"},
          {"name": "ArchUnit",    "directory": ".github/ci/archunit"},
          {"name": "ErrorProne",  "directory": ".github/ci/errorprone"},
          {"name": "SpotBugs",   "directory": ".github/ci/spotbugs"},
          {"name": "JUnit",      "directory": ".github/ci/junit"}
        ]
