name: Check Outdated Dependencies

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    uses: valkyrjaio/.github/.github/workflows/_java-check-outdated-dependencies.yml@09dea16834afe9016704cc57fa49f351bc55af6c
    secrets: inherit
    with:
      dependencies: |
        [
          {"name": "Spotless",    "directory": ".github/ci/spotless"},
          {"name": "ArchUnit",    "directory": ".github/ci/archunit"},
          {"name": "ErrorProne",  "directory": ".github/ci/errorprone"},
          {"name": "SpotBugs",   "directory": ".github/ci/spotbugs"},
          {"name": "JUnit",      "directory": ".github/ci/junit"}
        ]
