name: Create Major Release Version Branch

on: workflow_dispatch

run-name: Create new version for upcoming major release

jobs:
  create:
    uses: valkyrjaio/.github/.github/workflows/_create-version-branch.yml@13342de3aaf7e2c581c4b2420b59ef44a7b2c3b4
    secrets: inherit
