name: Create Major Release Version Branch

on: workflow_dispatch

run-name: Create new version for upcoming major release

jobs:
  create:
    uses: valkyrjaio/.github/.github/workflows/_create-version-branch.yml@47e8a34a503237c8dfef2af07e7f27c38621de0e
    secrets: inherit
