name: Create Major Release Version Branch

on: workflow_dispatch

run-name: Create new version for upcoming major release

jobs:
  create:
    uses: valkyrjaio/.github/.github/workflows/_create-version-branch.yml@983eb086a57533c52b7ce86a29b2d537aad838ed
    secrets: inherit
