name: Update Dependencies

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    uses: valkyrjaio/.github/.github/workflows/_java-update-dependencies.yml@09dea16834afe9016704cc57fa49f351bc55af6c
    secrets: inherit
    with:
      dependencies: |
        [
          {"name": "Application", "directory": "."},
          {"name": "Spotless",    "directory": ".github/ci/spotless"},
          {"name": "ArchUnit",    "directory": ".github/ci/archunit"},
          {"name": "ErrorProne",  "directory": ".github/ci/errorprone"},
          {"name": "SpotBugs",   "directory": ".github/ci/spotbugs"},
          {"name": "JUnit",      "directory": ".github/ci/junit"},
          {"name": "Sindri JUnit", "directory": ".github/ci/sindri-junit"}
        ]
