name: Update Dependencies

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    uses: valkyrjaio/.github/.github/workflows/_update-java-dependencies.yml@4cfdfbd49020f2e058ca90048876d05bb7819db8
    secrets: inherit
    with:
      dependencies: |
        [
          {"name": "Spotless",    "directory": ".github/ci/spotless"},
          {"name": "ArchUnit",    "directory": ".github/ci/archunit"},
          {"name": "ErrorProne",  "directory": ".github/ci/errorprone"},
          {"name": "SpotBugs",   "directory": ".github/ci/spotbugs"},
          {"name": "JUnit",      "directory": ".github/ci/junit"}
        ]
